<a href="https://colab.research.google.com/github/MDKorb/Notebooks/blob/main/Notebook5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
#Importar numpy
import numpy as np

In [6]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [7]:
#prueba: arreglo de unos de longitud 5
array_unos=np.ones(5)
print(array_unos)

[1. 1. 1. 1. 1.]


In [8]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array_diez=np.zeros(10)
array_diez[5]=10
print(array_diez)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [9]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
array_unos[3]=7
print(array_unos)

[1. 1. 1. 7. 1.]


In [4]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array_8_10=np.arange(9).reshape(3,3)
print(array_8_10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
array_100=np.random.rand(100)
print(array_100)

media = np.mean(array_100)
print("Media:", media)

varianza = np.var(array_100)
print("Varianza:", varianza)

[7.66637729e-01 5.65659815e-01 2.07319197e-01 7.76044479e-01
 6.47703921e-01 4.30618231e-01 7.27483292e-01 5.79936790e-01
 8.99020725e-01 1.68143888e-01 3.16196870e-01 6.67388331e-01
 3.46848442e-01 1.42802987e-01 5.16584544e-01 8.56252669e-01
 4.99790999e-01 6.45565025e-01 8.30310409e-01 6.52634031e-01
 5.34895654e-01 6.08961819e-02 3.45706084e-01 7.55603835e-01
 7.02969224e-01 4.76158263e-01 1.27917052e-04 2.40099087e-01
 8.30153419e-01 9.06611515e-01 5.18985852e-01 6.48095681e-01
 6.08752750e-01 1.81849220e-01 6.19784201e-01 3.69987580e-01
 1.05357683e-01 6.85195232e-01 5.50864051e-01 6.07726077e-01
 4.03331058e-01 4.04349133e-01 8.07554425e-01 2.04708931e-01
 2.14541394e-01 9.13613892e-01 3.57095591e-01 3.46307222e-01
 1.63903009e-01 1.59098683e-01 8.26086655e-01 4.71400543e-01
 4.63958149e-01 2.95215205e-01 1.81926053e-01 3.50515234e-01
 6.63180600e-01 7.07719820e-01 7.00341025e-01 3.77061102e-01
 3.17696165e-01 5.53685167e-01 8.92803103e-02 4.91638108e-01
 3.07621497e-01 2.447624

In [30]:
#pruba 5: crear arreglo de 50 numeros aleatorios y calcular media y varianza
array_50=np.random.rand(50)
print(array_50)
array_media50=np.mean(array_50)
print("Media:", array_media50)
array_varianza50=np.var(array_50)
print("Varianza:", array_varianza50)

[0.50841282 0.73405913 0.79841403 0.92517368 0.53533619 0.1100484
 0.22854375 0.12310781 0.66662419 0.98464139 0.72900485 0.41384448
 0.5372874  0.88280547 0.09838859 0.49163587 0.00330189 0.81341096
 0.55569189 0.75974482 0.75445177 0.84836223 0.43946948 0.9559774
 0.65540254 0.34554015 0.84002652 0.79393558 0.81264239 0.67035742
 0.84488458 0.22360562 0.72845074 0.71707166 0.18679082 0.34719996
 0.51950492 0.31888373 0.92313195 0.51048365 0.0541301  0.27993344
 0.29674875 0.2474954  0.83538673 0.77809911 0.19321439 0.63021041
 0.81193496 0.07499903]
Media: 0.5507560599439443
Varianza: 0.0789249296159941


In [16]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
array_100_sum=np.sum(array_100)/[len(array_100)]
print(array_100_sum)

[0.49841882]


In [17]:
#prueba6: la media es la suma de x0 a xn dividido n
array_50_sum=np.sum(array_50)/[len(array_50)]
print(array_50_sum)

[0.54884263]


In [32]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
array_100_varianza=np.sum((array_100-np.mean(array_100))**2)/[len(array_100)]
print(array_100_varianza)

[0.07377967]


In [27]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn.rand

array_aletorio=np.random.rand(5)
print(array_aletorio)

[0.36629786 0.12075462 0.74656064 0.05535301 0.47638366]
